[package]
name = "chess-core"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanorand = "0.7.0"

[dev-dependencies]
rayon = "1.7.0"
